version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Mapeia a porta 8080 do contêiner para a porta 8080 do host
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:mem:restaurantefiliais
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: ""
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9080/api/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: oscarfonts/h2 # Imagem do banco de dados H2
    ports:
      - "9092:9092" # Porta do H2 para acesso remoto
    environment:
      H2_OPTIONS: -ifNotExists
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9092"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  h2-data: